# Generated by Django 4.2.8 on 2023-12-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('avt', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('updates_at', models.DateField()),
                ('active', models.BooleanField()),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLyApp.userrole')),
            ],
        ),
    ]
