# Generated by Django 4.2.8 on 2023-12-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyApp', '0003_attribute_cart_category_paymenttype_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
