# Generated by Django 4.2.8 on 2023-12-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyApp', '0004_rename_updates_at_account_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuanLyApp.order'),
        ),
    ]
