# Generated by Django 4.2.8 on 2023-12-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyApp', '0006_product_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
