# Generated by Django 4.2.8 on 2023-12-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyApp', '0008_alter_account_created_at_alter_account_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='att',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.AddField(
            model_name='attribute',
            name='product',
            field=models.ManyToManyField(to='QuanLyApp.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='att',
            field=models.ManyToManyField(to='QuanLyApp.attribute'),
        ),
        migrations.DeleteModel(
            name='CategoryAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
